fix lambda push issue

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -98,9 +98,14 @@ jobs:
 
       - name: Zip Create-Event Lambda Code
         run: zip -r create-event.zip ./lambda/create-event
+
+      - name: Check Zip File Contents
+        run: |
+          unzip -l subscribe.zip || echo "❌ Zip is missing or invalid"
+      
       
       - name: Ensure Lambda Name is Provided
-        run: echo ${{ secrets.LAMBDA_CREATE_EVENT }} > hello.txt \
+        run: echo ${{ secrets.LAMBDA_CREATE_EVENT }} > hello.txt
              cat hello.txt
 
 
